name: _
publish_to: none
environment:
  sdk: ^3.13.0
workspace:
  - packages/aim_core
  - packages/aim_server
  - packages/aim_edge
  - packages/aim_cli
  - packages/aim_server_cors
  - packages/aim_server_cookie
  - packages/aim_server_testing
  - packages/aim_server_form
  - packages/aim_server_multipart
  - packages/aim_server_static
  - packages/aim_server_logger
  - packages/aim_server_sse
  - packages/aim_server_jwt
  - packages/aim_server_basic_auth
  - packages/aim_database
  - packages/aim_postgres
  - packages/aim_orm
  - packages/aim_orm_codegen
  - packages/aim_orm_postgres
  - examples/basic-sample
  - examples/orm-sample
  - examples/edge-sample
  - tools/release
  - packages/aim_orm_codegen/test/golden/fixtures/simple_table
  - packages/aim_orm_codegen/test/golden/fixtures/nullable_columns
  - packages/aim_orm_codegen/test/golden/fixtures/foreign_key
  - packages/aim_orm_codegen/test/golden/fixtures/multiple_fk
  - packages/aim_orm_codegen/test/golden/fixtures/nullable_fk
