import 'dart:convert';
import 'dart:typed_data';

import 'package:aim_mysql/src/exceptions.dart';
import 'package:aim_mysql/src/protocol/wire.dart';

/// Decodes [bytes] as UTF-8, turning a [FormatException] into
/// [MySqlProtocolException]. Mirrors the same conversion in `wire.dart`:
/// bytes that are all present but not valid UTF-8 leave a caller of this
/// file exactly as out of step as a short read does, so it should not have
/// to catch a second exception type to cover both.
String _decodeUtf8(List<int> bytes) {
  try {
    return utf8.decode(bytes);
  } on FormatException catch (e) {
    throw MySqlProtocolException('invalid UTF-8: $e');
  }
}

/// A packet the server sends back during authentication or in reply to a
/// command.
///
/// Sealed so that code handling a packet can `switch` on it exhaustively:
/// every subtype below is one this library can produce, and there is no
/// fourth kind hiding outside it. [parseAuthPhasePacket] and
/// [parseCommandPacket] each only ever return the subset of these that its
/// phase can actually send -- see their doc comments for which.
sealed class ServerPacket {}

/// The server did what was asked, with no rows to hand back -- or, for a
/// SELECT, the marker that a deprecated-EOF result set has just ended
/// (see [parseCommandPacket]).
final class OkPacket extends ServerPacket {
  OkPacket({
    required this.affectedRows,
    required this.lastInsertId,
    required this.statusFlags,
    required this.warnings,
    required this.info,
  });

  /// Rows inserted, updated or deleted by the statement. Zero for a SELECT.
  final int affectedRows;

  /// The auto-increment value generated by the statement, or `0` if it
  /// generated none.
  final int lastInsertId;

  /// The raw `SERVER_STATUS_*` bitmask. [inTransaction] reads the one bit
  /// this driver currently cares about; the rest is carried but not
  /// otherwise interpreted here.
  final int statusFlags;

  /// How many warnings the statement produced. The text of them is not
  /// sent with the OK packet -- a caller wanting it issues `SHOW WARNINGS`.
  final int warnings;

  /// Human-readable extra detail, e.g. `"Rows matched: 1  Changed: 1"` for
  /// an UPDATE. Empty, never null, when the server sent none.
  ///
  /// Read as a plain remainder of the packet, not a length-prefixed
  /// string. That is only correct because this driver never asks for
  /// `CLIENT_SESSION_TRACK`: asking for it would make the server
  /// length-prefix this field (and possibly append session-state-change
  /// data after it), changing this layout. Not asking for it removes a
  /// branch this driver has no use for anyway -- it does not read session
  /// tracker state.
  final String info;

  /// Whether `SERVER_STATUS_IN_TRANS` (`0x0001`) is set: an explicit
  /// transaction is open on the connection that sent this packet. Reading
  /// this is how the driver notices MySQL having committed one implicitly,
  /// which DDL statements do.
  bool get inTransaction => statusFlags & 0x0001 != 0;
}

/// The server refused the request.
final class ErrPacket extends ServerPacket {
  ErrPacket({
    required this.errorCode,
    required this.sqlState,
    required this.message,
  });

  /// The numeric error code, e.g. `1062` for a duplicate key. See
  /// `exceptions.dart` for how this drives [mysqlErrorFor]'s
  /// classification.
  final int errorCode;

  /// The five-character SQLSTATE sent alongside [errorCode]. Carried
  /// through for completeness; classification is on [errorCode], not
  /// this -- see `exceptions.dart`.
  final String sqlState;

  /// The server's own message text, in whatever language and character
  /// set the connection negotiated.
  final String message;
}

/// The legacy end-of-result-set marker. With `CLIENT_DEPRECATE_EOF`
/// negotiated -- which this driver always asks for -- the server sends
/// [OkPacket] instead, so this should not turn up in practice. Reading it
/// rather than crashing on it costs little and means a server that sends
/// one anyway is not fatal to talk to.
final class EofPacket extends ServerPacket {
  EofPacket({required this.warnings, required this.statusFlags});

  /// How many warnings are pending, exactly as in [OkPacket.warnings].
  final int warnings;

  /// The raw `SERVER_STATUS_*` bitmask, exactly as in
  /// [OkPacket.statusFlags].
  final int statusFlags;

  /// Whether `SERVER_STATUS_IN_TRANS` (`0x0001`) is set. See
  /// [OkPacket.inTransaction].
  bool get inTransaction => statusFlags & 0x0001 != 0;
}

/// The server wants authentication to continue with a different plugin
/// than the one the initial handshake named.
final class AuthSwitchRequest extends ServerPacket {
  AuthSwitchRequest({required this.pluginName, required this.scramble});

  /// The plugin to switch to, e.g. `caching_sha2_password`.
  final String pluginName;

  /// The new scramble to hash the password against, with the server's
  /// trailing NUL already dropped -- see [parseAuthPhasePacket].
  final Uint8List scramble;
}

/// A plugin-specific message sent during authentication, handed over
/// undecoded: what it means depends entirely on which plugin is running
/// (for `caching_sha2_password`, a single `0x03` or `0x04` status byte on
/// its fast path, or a PEM-encoded public key later in a full
/// authentication).
final class AuthMoreData extends ServerPacket {
  AuthMoreData(this.data);

  final Uint8List data;
}

/// The first packet of a command's reply that carries rows: the number of
/// columns in every row that follows, before any of the column
/// definitions or the rows themselves have been read.
final class ResultSetHeader extends ServerPacket {
  ResultSetHeader(this.columnCount);

  final int columnCount;
}

/// Parses an OK packet's body, having already established -- by whichever
/// marker byte led here, `0x00` or `0xfe` -- that this payload is one.
/// Both markers share this same layout past the first byte.
OkPacket _parseOk(Uint8List payload) {
  final reader = ByteReader(payload);
  reader.readUint8(); // The 0x00 or 0xfe marker; already acted on.

  final affectedRows = reader.readLengthEncodedInt();
  final lastInsertId = reader.readLengthEncodedInt();
  if (affectedRows == null || lastInsertId == null) {
    // The lenenc NULL marker (0xfb) is not a value a real OK packet ever
    // uses here; treating it as 0 would silently hide a stream that is
    // already out of step.
    throw MySqlProtocolException(
      "an OK packet's affected-rows or last-insert-id was the "
      'length-encoded-integer NULL marker (0xfb), which never happens for '
      'a real value',
    );
  }

  final statusFlags = reader.readUint16();
  final warnings = reader.readUint16();
  final info = _decodeUtf8(reader.readRemaining());

  return OkPacket(
    affectedRows: affectedRows,
    lastInsertId: lastInsertId,
    statusFlags: statusFlags,
    warnings: warnings,
    info: info,
  );
}

/// Parses an ERR packet's body, having already established -- by the
/// `0xff` marker byte that led here -- that this payload is one.
ErrPacket _parseErr(Uint8List payload) {
  final reader = ByteReader(payload);
  reader.readUint8(); // The 0xff marker; already acted on.

  final errorCode = reader.readUint16();
  reader.skip(1); // The '#' SQL-state marker byte; always this exact value.
  final sqlState = _decodeUtf8(reader.readBytes(5));
  final message = _decodeUtf8(reader.readRemaining());

  return ErrPacket(errorCode: errorCode, sqlState: sqlState, message: message);
}

/// Parses an auth switch request, having already established -- by the
/// `0xfe` marker byte that led here, during authentication -- that this
/// payload is one.
AuthSwitchRequest _parseAuthSwitchRequest(Uint8List payload) {
  final reader = ByteReader(payload);
  reader.readUint8(); // The 0xfe marker; already acted on.

  final pluginName = reader.readNulTerminatedString();
  final rest = reader.readRemaining();
  if (rest.isEmpty) {
    throw MySqlProtocolException(
      'auth switch request for "$pluginName" carried no scramble',
    );
  }
  // The server appends a trailing NUL to the scramble here -- unlike every
  // other use of "the rest of the packet" in this protocol, which carries
  // no terminator at all. Keeping it would feed the authentication plugin
  // a token one byte too long: the right length to look plausible, and
  // wrong enough that the server refuses it.
  final scramble = Uint8List.sublistView(rest, 0, rest.length - 1);

  return AuthSwitchRequest(pluginName: pluginName, scramble: scramble);
}

/// Parses a result set header, having already established that the
/// leading byte is neither `0x00`, `0xff`, `0xfb` nor a short `0xfe` --
/// i.e. that it is the first byte of a length-encoded column count.
ResultSetHeader _parseResultSetHeader(Uint8List payload) {
  final reader = ByteReader(payload);
  final columnCount = reader.readLengthEncodedInt();
  if (columnCount == null) {
    // Unreachable through parseCommandPacket, which turns a leading 0xfb
    // into a LOCAL-INFILE protocol error before this is ever called --
    // kept as a guard rather than a bare assumption, since a NULL column
    // count would otherwise read as 0 and be silently wrong.
    throw MySqlProtocolException(
      "a result set header's column count was the length-encoded-integer "
      'NULL marker (0xfb), which never happens for a real value',
    );
  }
  return ResultSetHeader(columnCount);
}

/// Parses one packet received while authenticating: after the initial
/// handshake, and after every auth-plugin exchange up to the final OK or
/// ERR.
///
/// The leading byte decides which of [OkPacket], [ErrPacket],
/// [AuthSwitchRequest] or [AuthMoreData] this is -- never guessed, always
/// this phase's own rule, because the same leading byte means something
/// else entirely in [parseCommandPacket]:
///
/// | leading byte | meaning |
/// |---|---|
/// | `0x00` | [OkPacket] -- authentication succeeded |
/// | `0xff` | [ErrPacket] |
/// | `0xfe` | [AuthSwitchRequest] |
/// | `0x01` | [AuthMoreData] |
/// | anything else | throws [MySqlProtocolException] |
///
/// Throws [MySqlProtocolException] if [payload] is empty, or its leading
/// byte is none of the above.
ServerPacket parseAuthPhasePacket(Uint8List payload) {
  if (payload.isEmpty) {
    throw MySqlProtocolException('empty payload during authentication');
  }
  final marker = payload[0];
  if (marker == 0x00) return _parseOk(payload);
  if (marker == 0xff) return _parseErr(payload);
  if (marker == 0xfe) return _parseAuthSwitchRequest(payload);
  if (marker == 0x01) return AuthMoreData(Uint8List.sublistView(payload, 1));
  throw MySqlProtocolException(
    'unexpected byte 0x${marker.toRadixString(16).padLeft(2, "0")} at the '
    'start of a packet received during authentication',
  );
}

/// Parses the first packet of a command's reply -- the very first packet
/// after sending a query, a prepared-statement execute, or similar.
///
/// | leading byte | meaning |
/// |---|---|
/// | `0x00` | [OkPacket] |
/// | `0xff` | [ErrPacket] |
/// | `0xfb` | throws [MySqlProtocolException] -- see below |
/// | `0xfe`, payload under 9 bytes | [OkPacket] -- a deprecated-EOF result-set end |
/// | anything else | [ResultSetHeader] -- a length-encoded column count |
///
/// The `0xfe` case exists because this driver negotiates
/// `CLIENT_DEPRECATE_EOF`, under which the server ends a result set with
/// an OK packet whose first byte is `0xfe` rather than `0x00`, to tell it
/// apart from a plain mid-result-set OK. Whether a `0xfe`-led payload is
/// that OK or is instead a column count that happens to need the `0xfe`
/// length-encoded-integer form (which itself needs 8 more bytes) is
/// decided by length: under 9 bytes total is never enough to hold that
/// form, so it can only be the short OK packet. This driver always
/// negotiates the binary protocol, under which the ambiguity cannot
/// actually arise -- a column count that huge does not happen -- but the
/// rule is implemented anyway, both because the wire does not promise
/// that and because a length check is far cheaper than being wrong about
/// it.
///
/// A `0xfb` marker here is the server asking for a local file
/// (`LOAD DATA LOCAL INFILE`). This driver never negotiates
/// `CLIENT_LOCAL_FILES` -- letting a server read arbitrary local files on
/// request is not a capability this driver grants itself -- so the server
/// has no basis to ask for one. One arriving means an earlier read left
/// the stream out of step, not that the feature was somehow reached
/// anyway; it is treated as a protocol failure rather than answered.
///
/// Throws [MySqlProtocolException] if [payload] is empty (never treated
/// as an empty OK packet), if it starts with `0xfb`, or if it is short
/// for whatever it turns out to be.
ServerPacket parseCommandPacket(Uint8List payload) {
  if (payload.isEmpty) {
    throw MySqlProtocolException(
      'empty payload where a command reply was expected',
    );
  }
  final marker = payload[0];
  if (marker == 0x00) return _parseOk(payload);
  if (marker == 0xff) return _parseErr(payload);
  if (marker == 0xfb) {
    throw MySqlProtocolException(
      'server sent a LOCAL INFILE request (0xfb); this driver never '
      'negotiates the localFiles capability, so something earlier in the '
      'stream was misread',
    );
  }
  if (marker == 0xfe && payload.length < 9) return _parseOk(payload);
  return _parseResultSetHeader(payload);
}

/// Parses a legacy EOF packet's body: `0xfe` followed by the warning
/// count and the status flags, in that order.
///
/// Note the order is warnings then status flags -- the opposite of
/// [OkPacket], which has status flags before warnings. That asymmetry is
/// the wire format's own, not a mistake here: EOF_Packet and OK_Packet
/// disagree about it, and both orders are implemented to match.
///
/// This driver negotiates `CLIENT_DEPRECATE_EOF`, so a real EOF packet
/// should not reach this in practice -- see [EofPacket].
EofPacket parseEofPacket(Uint8List payload) {
  final reader = ByteReader(payload);
  reader.readUint8(); // The 0xfe marker.

  final warnings = reader.readUint16();
  final statusFlags = reader.readUint16();

  return EofPacket(warnings: warnings, statusFlags: statusFlags);
}
