name: bench_cloud_functions_aim
description: Aim benchmark app as a Cloud Functions for Firebase HTTP function.
publish_to: none
environment:
  sdk: ^3.13.0
dependencies:
  aim_functions:
    path: ../../../../packages/aim_functions
  firebase_functions: ^0.8.0
dependency_overrides:
  aim_core:
    path: ../../../../packages/aim_core
dev_dependencies:
  build_runner: ^2.4.0
  lints: ^6.0.0
