name: aim_database
description: Database abstraction layer for Aim. Provides common interfaces for database drivers like aim_postgres.
version: 0.2.0
repository: https://github.com/dart-forge/aim
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
