name: aim_server_cors
description: CORS middleware for the aim_server framework.
version: 0.3.0
repository: https://github.com/dart-forge/aim
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  aim_core: ^0.3.0

dev_dependencies:
  aim_server: ^0.3.0
  aim_server_testing: ^0.3.0
  lints: ^6.0.0
  test: ^1.25.6
